apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytorch-gpu-deployment
  namespace: gpu-workloads
  labels:
    app: pytorch-gpu-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pytorch-gpu-app
  template:
    metadata:
      labels:
        app: pytorch-gpu-app
    spec:
      containers:
        - name: pytorch-gpu
          image: gerardrecinto/pytorch-gpu:latest
          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
              nvidia.com/gpu: "1"
            limits:
              cpu: "2"
              memory: "8Gi"
              nvidia.com/gpu: "1"
          command: ["python3", "train.py"]
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
